name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: 'dist'
      TARGET_DIR: ${{ '/var/www/sites/' + github.repository.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js in GitHub runner environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build
      
      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ env.SOURCE_DIR + '/*' }}
          target: ${{ env.TARGET_DIR }}
      
      - name: Restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ${{ env.TARGET_DIR }}
            cd ${{ env.TARGET_DIR }}
            npm install --production
            pm2 restart all

      - name: Notify completion
        run: echo "Deployment to DigitalOcean completed."